# build 
FROM node:22-slim AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

# run 
FROM node:22-slim AS runner

WORKDIR /app

ENV NODE_ENV=production

# only copy the production node_modules from the builder stage
COPY --from=builder /app/node_modules ./node_modules

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/index.js ./index.js 

EXPOSE 3000

CMD ["node", "index.js"]
