events { worker_connections 1024; }

http {
    upstream gin_backend {
        server gin-server:3000;
    }

    upstream node_backend {
        server node-server:3000;
    }

    server {
        listen 80;

        # requests to /auth go to the node server 
        location /auth {
            proxy_pass http://node_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # all other requests to the gin server 
        location / {
            proxy_pass http://gin_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

      }
}
